/*
Copyright 2018 The vegamcache-operator Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/sch00lb0y/vegamcache-operator/pkg/apis/vegamcache/v1alpha1"
	scheme "github.com/sch00lb0y/vegamcache-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VegamCachesGetter has a method to return a VegamCacheInterface.
// A group's client should implement this interface.
type VegamCachesGetter interface {
	VegamCaches(namespace string) VegamCacheInterface
}

// VegamCacheInterface has methods to work with VegamCache resources.
type VegamCacheInterface interface {
	Create(*v1alpha1.VegamCache) (*v1alpha1.VegamCache, error)
	Update(*v1alpha1.VegamCache) (*v1alpha1.VegamCache, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VegamCache, error)
	List(opts v1.ListOptions) (*v1alpha1.VegamCacheList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VegamCache, err error)
	VegamCacheExpansion
}

// vegamCaches implements VegamCacheInterface
type vegamCaches struct {
	client rest.Interface
	ns     string
}

// newVegamCaches returns a VegamCaches
func newVegamCaches(c *VegamcacheoperatorV1alpha1Client, namespace string) *vegamCaches {
	return &vegamCaches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vegamCache, and returns the corresponding vegamCache object, and an error if there is any.
func (c *vegamCaches) Get(name string, options v1.GetOptions) (result *v1alpha1.VegamCache, err error) {
	result = &v1alpha1.VegamCache{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vegamcaches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VegamCaches that match those selectors.
func (c *vegamCaches) List(opts v1.ListOptions) (result *v1alpha1.VegamCacheList, err error) {
	result = &v1alpha1.VegamCacheList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vegamcaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vegamCaches.
func (c *vegamCaches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vegamcaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a vegamCache and creates it.  Returns the server's representation of the vegamCache, and an error, if there is any.
func (c *vegamCaches) Create(vegamCache *v1alpha1.VegamCache) (result *v1alpha1.VegamCache, err error) {
	result = &v1alpha1.VegamCache{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vegamcaches").
		Body(vegamCache).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vegamCache and updates it. Returns the server's representation of the vegamCache, and an error, if there is any.
func (c *vegamCaches) Update(vegamCache *v1alpha1.VegamCache) (result *v1alpha1.VegamCache, err error) {
	result = &v1alpha1.VegamCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vegamcaches").
		Name(vegamCache.Name).
		Body(vegamCache).
		Do().
		Into(result)
	return
}

// Delete takes name of the vegamCache and deletes it. Returns an error if one occurs.
func (c *vegamCaches) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vegamcaches").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vegamCaches) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vegamcaches").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vegamCache.
func (c *vegamCaches) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VegamCache, err error) {
	result = &v1alpha1.VegamCache{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vegamcaches").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
